WITH mcb AS (
    SELECT 
        a.id,
        IF(b.bonding != '' AND b.bonding IS NOT NULL, b.bonding, a.sn) AS main_sn,
        b.lcm_id, 
        a.sn
    FROM displayer AS a 
    INNER JOIN displayer_realtime AS b ON a.id = b.id
)
SELECT 
    DATE(md.create_on) AS Date,
    DATE_FORMAT(md.create_on, '%r') AS TIME,
    md.time_zone AS TIME_ZONE,
    mcb.main_sn AS `Kiosk/Display_SN`,
    CASE
        WHEN mcb.lcm_id = 1 THEN 'Front'
        ELSE 'Back'
    END AS Side,
    mcb.sn AS LCM_SN,
    IFNULL(MAX(CAST(CASE WHEN md.cmd = 78 THEN JSON_UNQUOTE(JSON_EXTRACT(md.args, '$.B'))  END AS UNSIGNED)),0) AS B,
    IFNULL(MAX(CAST(CASE WHEN md.cmd = 78 THEN JSON_UNQUOTE(JSON_EXTRACT(md.args, '$.F'))  END AS UNSIGNED)),0) AS F,
    IFNULL(MAX(CAST(CASE WHEN md.cmd = 78 THEN JSON_UNQUOTE(JSON_EXTRACT(md.args, '$.O'))  END AS UNSIGNED)),0) AS O,
    IFNULL(MAX(CAST(CASE WHEN md.cmd = 78 THEN JSON_UNQUOTE(JSON_EXTRACT(md.args, '$.P'))  END AS UNSIGNED)),0) AS P,
    IFNULL(MAX(CAST(CASE WHEN md.cmd = 78 THEN JSON_UNQUOTE(JSON_EXTRACT(md.args, '$.S'))  END AS UNSIGNED)),0) AS S,
    IFNULL(MAX(CAST(CASE WHEN md.cmd = 78 THEN JSON_UNQUOTE(JSON_EXTRACT(md.args, '$.OS'))  END AS UNSIGNED)),0) AS OS,
    IFNULL(MAX(CAST(CASE WHEN md.cmd = 78 THEN JSON_UNQUOTE(JSON_EXTRACT(md.args, '$.SF'))  END AS UNSIGNED)),0) AS SF,
    IFNULL(MAX(CAST(CASE WHEN md.cmd = 78 THEN JSON_UNQUOTE(JSON_EXTRACT(md.args, '$.T1'))  END AS UNSIGNED)),0) AS T1,
    IFNULL(MAX(CAST(CASE WHEN md.cmd = 78 THEN JSON_UNQUOTE(JSON_EXTRACT(md.args, '$.T2'))  END AS UNSIGNED)),0) AS T2,
    IFNULL(MAX(CAST(CASE WHEN md.cmd = 78 THEN JSON_UNQUOTE(JSON_EXTRACT(md.args, '$.ResH'))  END AS UNSIGNED)),0) AS RESH,
    IFNULL(MAX(CAST(CASE WHEN md.cmd = 78 THEN JSON_UNQUOTE(JSON_EXTRACT(md.args, '$.ResV'))  END AS UNSIGNED)),0) AS RESV,
    IFNULL(MAX(CAST(CASE WHEN md.cmd = 78 THEN JSON_UNQUOTE(JSON_EXTRACT(md.args, '$.OS_NORMAL'))  END AS UNSIGNED)),0) AS OS_Normal,
    IFNULL(MAX(CAST(CASE WHEN md.cmd = 78 THEN JSON_UNQUOTE(JSON_EXTRACT(md.args, '$.BootCompleted'))  END AS UNSIGNED)),0) AS BOOTCOMPLETED,
    IFNULL(MAX(CAST(CASE WHEN md.cmd = 78 THEN JSON_UNQUOTE(JSON_EXTRACT(md.args, '$.ServiceStatus'))  END AS UNSIGNED)),0) AS SERVICESTATUS,
    IFNULL(MAX(CAST(CASE WHEN md.cmd = 160 THEN JSON_UNQUOTE(JSON_EXTRACT(md.args, '$.AC.C'))  END AS UNSIGNED)),0) AS C,
    IFNULL(MAX(CAST(CASE WHEN md.cmd = 160 THEN JSON_UNQUOTE(JSON_EXTRACT(md.args, '$.AC.P'))  END AS UNSIGNED)),0) AS `P'`,
    IFNULL(MAX(CAST(CASE WHEN md.cmd = 160 THEN JSON_UNQUOTE(JSON_EXTRACT(md.args, '$.AC.V'))  END AS UNSIGNED)),0) AS V,
    IFNULL(MAX(CAST(CASE WHEN md.cmd = 160 THEN JSON_UNQUOTE(JSON_EXTRACT(md.args, '$.DC.V1'))  END AS UNSIGNED)),0) AS V1,
    IFNULL(MAX(CAST(CASE WHEN md.cmd = 160 THEN JSON_UNQUOTE(JSON_EXTRACT(md.args, '$.DC.V2'))  END AS UNSIGNED)),0) AS V2,
    IFNULL(MAX(CAST(CASE WHEN md.cmd = 160 THEN JSON_UNQUOTE(JSON_EXTRACT(md.args, '$.DC.V3'))  END AS UNSIGNED)),0) AS V3,
    IFNULL(MAX(CAST(CASE WHEN md.cmd = 160 THEN JSON_UNQUOTE(JSON_EXTRACT(md.args, '$.DC.V4'))  END AS UNSIGNED)),0) AS V4,
    IFNULL(MAX(CAST(CASE WHEN md.cmd = 160 THEN JSON_UNQUOTE(JSON_EXTRACT(md.args, '$.DC2.V5'))  END AS UNSIGNED)),0) AS V5,
    IFNULL(MAX(CAST(CASE WHEN md.cmd = 160 THEN JSON_UNQUOTE(JSON_EXTRACT(md.args, '$.DC2.V6'))  END AS UNSIGNED)),0) AS V6,
    IFNULL(MAX(CAST(CASE WHEN md.cmd = 160 THEN JSON_UNQUOTE(JSON_EXTRACT(md.args, '$.DC2.V7'))  END AS UNSIGNED)),0) AS V7,
    IFNULL(MAX(CAST(CASE WHEN md.cmd = 160 THEN JSON_UNQUOTE(JSON_EXTRACT(md.args, '$.DC2.V8'))  END AS UNSIGNED)),0) AS V8,
    IFNULL(MAX(CAST(CASE WHEN md.cmd = 160 THEN JSON_UNQUOTE(JSON_EXTRACT(md.args, '$.DC3.V9'))  END AS UNSIGNED)),0) AS V9,
    IFNULL(MAX(CAST(CASE WHEN md.cmd = 160 THEN JSON_UNQUOTE(JSON_EXTRACT(md.args, '$.DC3.V10'))  END AS UNSIGNED)),0) AS V10,
    IFNULL(MAX(CAST(CASE WHEN md.cmd = 160 THEN JSON_UNQUOTE(JSON_EXTRACT(md.args, '$.DC3.V11'))  END AS UNSIGNED)),0) AS V11,
    IFNULL(MAX(CAST(CASE WHEN md.cmd = 160 THEN JSON_UNQUOTE(JSON_EXTRACT(md.args, '$.LC_Temperature.LC'))  END AS UNSIGNED)),0) AS LC,
    IFNULL(MAX(CAST(CASE WHEN md.cmd = 160 THEN JSON_UNQUOTE(JSON_EXTRACT(md.args, '$.LC_Temperature.Env'))  END AS UNSIGNED)),0) AS ENV,
    IFNULL(MAX(CAST(CASE WHEN md.cmd = 160 THEN JSON_UNQUOTE(JSON_EXTRACT(md.args, '$.LC_Temperature.LC_IR'))  END AS UNSIGNED)),0) AS LC_IR,
    IFNULL(MAX(CAST(CASE WHEN md.cmd = 160 THEN JSON_UNQUOTE(JSON_EXTRACT(md.args, '$.LC_Temperature.Cabinet'))  END AS UNSIGNED)),0) AS CABINET,
    IFNULL(MAX(CAST(CASE WHEN md.cmd = 160 THEN JSON_UNQUOTE(JSON_EXTRACT(md.args, '$.LC_Temperature.LC_BOTTOM'))  END AS UNSIGNED)),0) AS LC_BOTTOM,
    IFNULL(MAX(CAST(CASE WHEN md.cmd = 160 THEN JSON_UNQUOTE(JSON_EXTRACT(md.args, '$.TemperatureControl.BSL'))  END AS UNSIGNED)),0) AS BSL,
    IFNULL(MAX(CAST(CASE WHEN md.cmd = 160 THEN JSON_UNQUOTE(JSON_EXTRACT(md.args, '$.TemperatureControl.CDM'))  END AS UNSIGNED)),0) AS CDM,
    IFNULL(MAX(CAST(CASE WHEN md.cmd = 160 THEN JSON_UNQUOTE(JSON_EXTRACT(md.args, '$.TemperatureControl.HTM'))  END AS UNSIGNED)),0) AS HTM,
    IFNULL(MAX(CAST(CASE WHEN md.cmd = 160 THEN JSON_UNQUOTE(JSON_EXTRACT(md.args, '$.TemperatureControl.SBM'))  END AS UNSIGNED)),0) AS SBM,
    IFNULL(MAX(CAST(CASE WHEN md.cmd = 160 THEN JSON_UNQUOTE(JSON_EXTRACT(md.args, '$.TemperatureControl.WSL'))  END AS UNSIGNED)),0) AS WSL,
    IFNULL(MAX(CAST(CASE WHEN md.cmd = 160 THEN JSON_UNQUOTE(JSON_EXTRACT(md.args, '$.TemperatureControl.WUM'))  END AS UNSIGNED)),0) AS WUM,
    IFNULL(MAX(CAST(CASE WHEN md.cmd = 160 THEN JSON_UNQUOTE(JSON_EXTRACT(md.args, '$.TemperatureControl.FFST'))  END AS UNSIGNED)),0) AS FFST,
    IFNULL(MAX(CAST(CASE WHEN md.cmd = 160 THEN JSON_UNQUOTE(JSON_EXTRACT(md.args, '$.TemperatureControl.EX_FS'))  END AS UNSIGNED)),0) AS EX_FS,
    IFNULL(MAX(CAST(CASE WHEN md.cmd = 160 THEN JSON_UNQUOTE(JSON_EXTRACT(md.args, '$.TemperatureControl.TOP_FS'))  END AS UNSIGNED)),0) AS TOP_FS,
    IFNULL(MAX(CAST(CASE WHEN md.cmd = 160 THEN JSON_UNQUOTE(JSON_EXTRACT(md.args, '$.TemperatureControl.ANGLE_1'))  END AS UNSIGNED)),0) AS ANGLE_1,
    IFNULL(MAX(CAST(CASE WHEN md.cmd = 160 THEN JSON_UNQUOTE(JSON_EXTRACT(md.args, '$.TemperatureControl.ANGLE_2'))  END AS UNSIGNED)),0) AS ANGLE_2,
    IFNULL(MAX(CAST(CASE WHEN md.cmd = 160 THEN JSON_UNQUOTE(JSON_EXTRACT(md.args, '$.TemperatureControl.FanAlarm'))  END AS UNSIGNED)),0) AS FANALARM,
    IFNULL(MAX(CAST(CASE WHEN md.cmd = 160 THEN JSON_UNQUOTE(JSON_EXTRACT(md.args, '$.TemperatureControl.BOTTOM_FS'))  END AS UNSIGNED)),0) AS BOTTOM_FS,
    IFNULL(MAX(CAST(CASE WHEN md.cmd = 160 THEN JSON_UNQUOTE(JSON_EXTRACT(md.args, '$.TemperatureControl.GRAVITY_1'))  END AS UNSIGNED)),0) AS GRAVITY_1,
    IFNULL(MAX(CAST(CASE WHEN md.cmd = 160 THEN JSON_UNQUOTE(JSON_EXTRACT(md.args, '$.TemperatureControl.GRAVITY_2'))  END AS UNSIGNED)),0) AS GRAVITY_2,
    IFNULL(MAX(CAST(CASE WHEN md.cmd = 160 THEN JSON_UNQUOTE(JSON_EXTRACT(md.args, '$.TemperatureControl.GRAVITY_3'))  END AS UNSIGNED)),0) AS GRAVITY_3,
    IFNULL(MAX(CAST(CASE WHEN md.cmd = 160 THEN JSON_UNQUOTE(JSON_EXTRACT(md.args, '$.TemperatureControl.QuietMode'))  END AS UNSIGNED)),0) AS QUIETMODE,
    IFNULL(MAX(CAST(CASE WHEN md.cmd = 160 THEN JSON_UNQUOTE(JSON_EXTRACT(md.args, '$.TemperatureControl.DoorSwitch'))  END AS UNSIGNED)),0) AS DOORSWITCH,
    IFNULL(MAX(CAST(CASE WHEN md.cmd = 160 THEN JSON_UNQUOTE(JSON_EXTRACT(md.args, '$.TemperatureControl.ECB_Status'))  END AS UNSIGNED)),0) AS ECB_STATUS,
    IFNULL(MAX(CAST(CASE WHEN md.cmd = 160 THEN JSON_UNQUOTE(JSON_EXTRACT(md.args, '$.TemperatureControl.LCM_Status'))  END AS UNSIGNED)),0) AS LCM_STATUS,
    IFNULL(MAX(CAST(CASE WHEN md.cmd = 160 THEN JSON_UNQUOTE(JSON_EXTRACT(md.args, '$.TemperatureControl.MAIN_FAN_EN'))  END AS UNSIGNED)),0) AS MAIN_FAN_EN,
    IFNULL(MAX(CAST(CASE WHEN md.cmd = 160 THEN JSON_UNQUOTE(JSON_EXTRACT(md.args, '$.TemperatureControl.MainFanAlarm'))  END AS UNSIGNED)),0) AS MAINFANALARM,
    IFNULL(MAX(CAST(CASE WHEN md.cmd = 160 THEN JSON_UNQUOTE(JSON_EXTRACT(md.args, '$.TemperatureControl.DoorFanStatus'))  END AS UNSIGNED)),0) AS DOORFANSTATUS,
    IFNULL(MAX(CAST(CASE WHEN md.cmd = 160 THEN JSON_UNQUOTE(JSON_EXTRACT(md.args, '$.TemperatureControl.EnvironmentTP'))  END AS UNSIGNED)),0) AS ENVIORNMENTTP,
    IFNULL(MAX(CAST(CASE WHEN md.cmd = 160 THEN JSON_UNQUOTE(JSON_EXTRACT(md.args, '$.TemperatureControl.DCVoltageAlarm'))  END AS UNSIGNED)),0) AS DCVOLTAGEALARM,
    IFNULL(MAX(CAST(CASE WHEN md.cmd = 160 THEN JSON_UNQUOTE(JSON_EXTRACT(md.args, '$.TemperatureControl.LowVoltageMode'))  END AS UNSIGNED)),0) AS LOWVOLTAGEMODE,
    IFNULL(MAX(CAST(CASE WHEN md.cmd = 160 THEN JSON_UNQUOTE(JSON_EXTRACT(md.args, '$.TemperatureControl.ProtectionMode'))  END AS UNSIGNED)),0) AS PROTECTIONMODE,
    IFNULL(MAX(CAST(CASE WHEN md.cmd = 160 THEN JSON_UNQUOTE(JSON_EXTRACT(md.args, '$.TemperatureControl.BackLightStatus'))  END AS UNSIGNED)),0) AS BACKLIGHTSTATUS,
    IFNULL(MAX(CAST(CASE WHEN md.cmd = 160 THEN JSON_UNQUOTE(JSON_EXTRACT(md.args, '$.TemperatureControl.FanFullSpeedMode'))  END AS UNSIGNED)),0) AS FANFULLSPEEDMODE,
    IFNULL(MAX(CAST(CASE WHEN md.cmd = 160 THEN JSON_UNQUOTE(JSON_EXTRACT(md.args, '$.TemperatureControl.BrightnessHighZone'))  END AS UNSIGNED)),0) AS BRIGHTNESSHHIGHZONE,
    IFNULL(MAX(CAST(CASE WHEN md.cmd = 160 THEN JSON_UNQUOTE(JSON_EXTRACT(md.args, '$.TemperatureControl.CirculationFailure'))  END AS UNSIGNED)),0) AS CIRCULATIONFAILURE,
    IFNULL(MAX(CAST(CASE WHEN md.cmd = 160 THEN JSON_UNQUOTE(JSON_EXTRACT(md.args, '$.TemperatureControl.ThermalProtection2'))  END AS UNSIGNED)),0) AS THERMALPROTECTION2,
    IFNULL(MAX(CAST(CASE WHEN md.cmd = 160 THEN JSON_UNQUOTE(JSON_EXTRACT(md.args, '$.TemperatureControl.OverHeatProtectionEn'))  END AS UNSIGNED)),0) AS OVERHEATPROTECTIONEN,
    IFNULL(MAX(CAST(CASE WHEN md.cmd = 160 THEN JSON_UNQUOTE(JSON_EXTRACT(md.args, '$.Humidity.H'))  END AS UNSIGNED)),0) AS H,
    IFNULL(MAX(CAST(CASE WHEN md.cmd = 160 THEN JSON_UNQUOTE(JSON_EXTRACT(md.args, '$.Humidity.H2'))  END AS UNSIGNED)),0) AS H2,
    IFNULL(MAX(CAST(CASE WHEN md.cmd = 176 THEN JSON_UNQUOTE(JSON_EXTRACT(md.args, '$.SBT'))  END AS UNSIGNED)),0) AS SBT,
    IFNULL(MAX(CAST(CASE WHEN md.cmd = 176 THEN JSON_UNQUOTE(JSON_EXTRACT(md.args, '$.AmbBright'))  END AS UNSIGNED)),0) AS AMBBRIGHT,
    IFNULL(MAX(CAST(CASE WHEN md.cmd = 176 THEN JSON_UNQUOTE(JSON_EXTRACT(md.args, '$.Threshold'))  END AS UNSIGNED)),0) AS THRESHOLD,
    IFNULL(MAX(CAST(CASE WHEN md.cmd = 186 THEN JSON_UNQUOTE(JSON_EXTRACT(md.args, '$.DO'))  END AS UNSIGNED)),0) AS DO
FROM mcb_detail_record AS md
INNER JOIN mcb ON mcb.id = md.mcb_id
WHERE md.cmd IN (78, 160, 176, 186) 
  AND md.create_on BETWEEN '2024-08-01 00:00:00' AND '2024-08-01 23:59:59'
  AND mcb.main_sn = (
    SELECT 
        IF(b.bonding != '' AND b.bonding IS NOT NULL, b.bonding, a.sn) AS main_sn
    FROM displayer AS a 
    INNER JOIN displayer_realtime AS b ON a.id = b.id
    WHERE a.id = 2330
)
GROUP BY md.create_on, md.time_zone, mcb.main_sn, mcb.lcm_id, mcb.sn
ORDER BY mcb.main_sn, md.create_on, mcb.lcm_id;
